
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reminders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.xml